import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import BodyComponent from "./components/BodyComponent";

const inter = Inter({ subsets: ["latin"] });

/**
 * ICountry interface
 * @interface ICountry
 * @TODO : revoir native name , currency et language
 */

export interface ICountry {
  flags: {
    svg: string;
    png: string;
  };
  name: {
    common: string;
    nativeName: {
      ara: { common: string }; // native name in arabic  ???????
    };
  };
  population: number;
  region: string;
  subregion: string;
  capital: string;
  topLevelDomain: string[];
  currencies: {
    AED: { name: string; symbol: string }; // CURRENCY ???????
  };
  languages: {
    ara: string; // language ???????
  };
  bordercountries: string[];
}


export default function Home() {
  // fetching data from the api
  const [countries, setCountries] = useState<ICountry[]>([]);

  useEffect(() => {
    fetch("https://restcountries.com/v3.1/all")
      // fetch("https://restcountries.com/v2/all?fields=flag,name,region,capital")
      .then((res) => res.json())
      .then((data) => {
        setCountries(data);
      })
      .catch((err) => console.log(err));
  }, []);

  return (
    <>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyComponent countries={countries} />
    </>
  );
}
